package com.kodedu.copilot.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents a plan generated by Copilot in Plan mode.
 */
public class CopilotPlan {

    public enum StepStatus {
        PENDING, APPROVED, REJECTED, COMPLETED
    }

    public static class PlanStep {
        private String description;
        private StepStatus status;
        private String filePath;
        private String oldContent;
        private String newContent;

        public PlanStep() {
            this.status = StepStatus.PENDING;
        }

        public PlanStep(String description) {
            this();
            this.description = description;
        }

        public String getDescription() {
            return description;
        }

        public void setDescription(String description) {
            this.description = description;
        }

        public StepStatus getStatus() {
            return status;
        }

        public void setStatus(StepStatus status) {
            this.status = status;
        }

        public String getFilePath() {
            return filePath;
        }

        public void setFilePath(String filePath) {
            this.filePath = filePath;
        }

        public String getOldContent() {
            return oldContent;
        }

        public void setOldContent(String oldContent) {
            this.oldContent = oldContent;
        }

        public String getNewContent() {
            return newContent;
        }

        public void setNewContent(String newContent) {
            this.newContent = newContent;
        }
    }

    private String title;
    private String description;
    private final List<PlanStep> steps;

    public CopilotPlan() {
        this.steps = new ArrayList<>();
    }

    public CopilotPlan(String title, String description) {
        this();
        this.title = title;
        this.description = description;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public List<PlanStep> getSteps() {
        return steps;
    }

    public void addStep(PlanStep step) {
        steps.add(step);
    }

    public long getCompletedCount() {
        return steps.stream().filter(s -> s.getStatus() == StepStatus.COMPLETED).count();
    }

    public long getApprovedCount() {
        return steps.stream().filter(s -> s.getStatus() == StepStatus.APPROVED).count();
    }
}
