start uglifyjs --screw-ie8 -c -o buffhelper.js -- buffhelper.js
start uglifyjs --screw-ie8 -c -o jade.js -- jade.js
start uglifyjs --screw-ie8 -c -o asciidoctor-browser.js -- asciidoctor-browser.js
start uglifyjs --screw-ie8 -c -o asciidoctor-docbook.js -- asciidoctor-docbook.js
start uglifyjs --screw-ie8 -c -o asciidoctor-data-line.js -- asciidoctor-data-line.js
start uglifyjs --screw-ie8 -c -o asciidoctor-chart-block.js -- asciidoctor-chart-block.js
start uglifyjs --screw-ie8 -c -o asciidoctor-tree-block.js -- asciidoctor-tree-block.js
start uglifyjs --screw-ie8 -c -o asciidoctor-uml-block.js -- asciidoctor-uml-block.js
start uglifyjs --screw-ie8 -c -o asciidoctor-reveal.js -- asciidoctor-reveal.js
start uglifyjs --screw-ie8 -c -o asciidoctor-deck.js -- asciidoctor-deck.js
start uglifyjs --screw-ie8 -c -o outliner.js -- outliner.js
start uglifyjs --screw-ie8 -c -o webworker-converters.js -- webworker-converters.js
start uglifyjs --screw-ie8 -c -o editor.js -- editor.js
start uglifyjs --screw-ie8 -c -o preview.js -- preview.js
start uglifyjs --screw-ie8 -c -o to-markdown.js -- to-markdown.js
start uglifyjs --screw-ie8 -c -o reveal-extensions.js -- reveal-extensions.js
start uglifyjs --screw-ie8 -c -o deck-extensions.js -- deck-extensions.js
start uglifyjs --screw-ie8 -c -o apply-replacements.js -- apply-replacements.js
start uglifyjs --screw-ie8 -c -o converters.js -- converters.js
start uglifyjs --screw-ie8 -c -o scroller.js -- scroller.js
start uglifyjs --screw-ie8 -c -o marked.js -- marked.js
start uglifyjs --screw-ie8 -c -o marked-extension.js -- marked-extension.js
start uglifyjs --screw-ie8 -c -o webworker.js -- webworker.js
start uglifyjs --screw-ie8 -c -o asciidoctor-odf.js -- asciidoctor-odf.js
start uglifyjs --screw-ie8 -c -o asciidoctor-image-size-info.js -- asciidoctor-image-size-info.js
