# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
  pull_request:
      
env:
  INSTALL4J_URL: https://download.ej-technologies.com/install4j/install4j_linux-x64_10_0_4.tar.gz
  LICENSE_KEY_10: ${{ secrets.LICENSE_KEY_10 }}
  MAC_CODE_SIGN_P12: ${{ secrets.MAC_CODE_SIGN_P12 }}
  WIN_CODE_SIGN_PFX: ${{ secrets.WIN_CODE_SIGN_PFX }}
  MAC_KEYSTORE_PASSWORD: ${{ secrets.MAC_KEYSTORE_PASSWORD }}
  MAC_APPLE_ID: ${{ secrets.MAC_APPLE_ID }}
  MAC_APP_PASSWORD: ${{ secrets.MAC_APP_PASSWORD }}
  WIN_KEYSTORE_PASSWORD: ${{ secrets.WIN_KEYSTORE_PASSWORD }}

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 20
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'temurin'
        cache: maven
    - name: Download install4j
      run: |
         wget --tries=3 ${{ env.INSTALL4J_URL }}
         tar zxvf install4j_linux-x64_10_0_4.tar.gz
    - name: Add signing key for MAC
      run: 'echo "$MAC_CODE_SIGN_P12" | base64 -d  >mac_code_sign.p12'
    - name: Add signing key for WIN
      run: 'echo "$WIN_CODE_SIGN_PFX" | base64 -d  >win_code_sign.pfx'
    - name: Build with install4j
      run: mvn -B -DskipTests -T 1.5C -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=600 clean install -P install4j  
    - name: Prepare release notes
      run: |
        awk -e '/^## /{a+=1} {if(a>1)exit} {if(a==1){print $0}}' CHANGELOG.md >RELEASE_MESSAGE.md
        printf '\n## Files checksums\n| File | SHA 256 |\n| --- | --- |\n' >>RELEASE_MESSAGE.md
        awk -e '{print"|"$2"|"$1"|"}' <target/media/sha256sums >>RELEASE_MESSAGE.md
    - name: Release draft
      uses: softprops/action-gh-release@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        body_path: RELEASE_MESSAGE.md
        draft: false
        prerelease: false
        fail_on_unmatched_files: true
        files: |
          target/media/AsciidocFX_Mac.dmg
          target/media/AsciidocFX_Mac_M1.dmg
          target/media/AsciidocFX_Linux.tar.gz
          target/media/AsciidocFX_Linux_Deb.deb
          target/media/AsciidocFX_Linux_Rpm.rpm
          target/media/AsciidocFX_Windows.exe
          target/media/AsciidocFX_Windows.zip
          target/media/updates.xml  
